### ISSUE TITLE
describe how to get SHA256 digest

### ISSUE THREAD

**Issue by jklynch** [nsls-ii-forge/docs#5]
In section "Manually create a recipe or use the existing recipe" there should be instructions for calculating the SHA256 digest from a source archive.

**Comment by jklynch** [comment]
for example
$ sha256sum 2.1.11.tar.gz 
de4e37098170d87f4a702cc6fe51491e435f728a629af9461c400064a262e25d  2.1.11.tar.gz

**Comment by mrakitin** [comment]
Conda forge folks recommend to use `openssl sha256 <file>`.

**Comment by jklynch** [comment]
Yes!
