### ISSUE TITLE
Add index.html

### ISSUE THREAD

**Issue by mrakitin** [nsls-ii-forge/docs#7]
See https://github.com/caproto/caproto.github.io/commit/deffdde814d714b7b90f1878869aee46b6ea7bdc for a nice page at https://nsls-ii-forge.github.io instead of the 404 error. Thanks to @danielballan for having a solution!

**Comment by mrakitin** [comment]
I think it's not possible with the `gh-pages` _branch_ approach, unlike in caproto it's done via a separate _repo_ https://github.com/caproto/caproto.github.io.

**Comment by danielballan** [comment]
True. Note that you _can_ have a mixture if you want to. That is, you can create a nsls-ii-forge.github.io repo and put an index.html page there, and your gh-pages branches will continue to work. It's a bit confusing, but it works.

**Comment by mrakitin** [comment]
Interesting, we may try it. Is it going to be a repo with a single `index.html` file?

**Comment by mrakitin** [comment]
The repo and the suggested file are there: https://github.com/nsls-ii-forge/nsls-ii-forge.github.io/blob/master/index.html. Works now: https://nsls-ii-forge.github.io -> https://nsls-ii-forge.github.io/docs automatically!

Thanks for the hint, @danielballan! Closing as resolved.
